stages:
  - build
  - test

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

build:
  stage: build
  script:
    - docker build -t rocket-chat .

test:
  stage: test
  script:
    - docker-compose up -d
    - docker-compose exec rocketchat curl -f http://localhost:3000 || exit 1
